In [2]:
import os
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import sklearn

if os.path.exists('/kaggle/input'):
    print("Successfully connected to Kaggle's dataset environment")
    #for root, dirs, files in os.walk('/kaggle/input'):
     #   for file in files[:5]: 
      #      print(os.path.join(root, file))
else:
    print("Not connected, code running locally")

Successfully connected to Kaggle's dataset environment

## Ecg Subset

In [3]:
#ecg data
#?? understand folder structure

'''
ecg_path = '/kaggle/input/datasets/sarabhian/d1namo-ecg-glucose-data/diabetes_subset_ecg_data/diabetes_subset_ecg_data/001/sensor_data'
ecg1 = pd.read_csv(ecg_path + '/2014_10_01-10_09_39/2014_10_01-10_09_39_ECG.csv')
ecg2 = pd.read_csv(ecg_path + '/2014_10_02-10_56_44/2014_10_02-10_56_44_ECG.csv')
ecg3 = pd.read_csv(ecg_path + '/2014_10_03-06_36_24/2014_10_03-06_36_24_ECG.csv')
ecg4 = pd.read_csv(ecg_path + '/2014_10_04-06_34_57/2014_10_04-06_34_57_ECG.csv')

ecg_data = pd.concat([ecg1, ecg2, ecg3, ecg4])
ecg_data['Time'] = pd.to_datetime(ecg_data['Time'])
ecg_data.sort_values(by='Time', inplace=True)
ecg_data
'''

#ecg data day 1
ecg_path = '/kaggle/input/datasets/sarabhian/d1namo-ecg-glucose-data/diabetes_subset_ecg_data/diabetes_subset_ecg_data/001/sensor_data'
ecg1 = pd.read_csv(ecg_path + '/2014_10_01-10_09_39/2014_10_01-10_09_39_ECG.csv')

In [4]:
ecg1.head()

                      Time  EcgWaveform
0  01/10/2014 10:09:39.417          297
1  01/10/2014 10:09:39.421          297
2  01/10/2014 10:09:39.425          297
3  01/10/2014 10:09:39.429          297
4  01/10/2014 10:09:39.433          297

## Food, Glucose, Insulin Subset

In [5]:
#food, glucose, and insulin data
food_data = pd.read_csv('/kaggle/input/datasets/sarabhian/d1namo-ecg-glucose-data/diabetes_subset_pictures-glucose-food-insulin/diabetes_subset_pictures-glucose-food-insulin/001/food.csv')
glucose_data = pd.read_csv('/kaggle/input/datasets/sarabhian/d1namo-ecg-glucose-data/diabetes_subset_pictures-glucose-food-insulin/diabetes_subset_pictures-glucose-food-insulin/001/glucose.csv')
insulin_data = pd.read_csv('/kaggle/input/datasets/sarabhian/d1namo-ecg-glucose-data/diabetes_subset_pictures-glucose-food-insulin/diabetes_subset_pictures-glucose-food-insulin/001/insulin.csv')

In [13]:
food_data

,picture,description,calories,balance,quality,datetime
0,001.jpg,Iceberg lettuce with olive oil and vinegar,357,Unbalance,Good quality,2014:10:01 19:27:49
1,002.jpg,"Tuna salade with boiled egg, asiago cheese an...",866,Unbalance,Good quality,2014:10:01 19:32:00
2,003.jpg,Asiago cheese,190,Unbalance,Good quality,2014:10:01 19:43:59
3,004.jpg,"Lemon yogurt, asiago cheese and bread with kiwi",1063,Balance,Good quality,2014:10:02 10:11:16
4,005.jpg,Tomatoes with cheese and bread,979,Unbalance,Good quality,2014:10:02 19:34:03
5,006.jpg,Tomatoes,42,Unbalance,Good quality,2014:10:02 19:44:51
6,007.jpg,White bread,262,Unbalance,Low quality,2014:10:03 10:08:48
7,008.jpg,Lettuce of tomatoes and carrots salad with oli...,130,Unbalance,Good quality,2014:10:03 12:37:00
8,009.jpg,Steak tartar and frites potatoes,607,Unbalance,Medium quality,2014:10:03 12:59:00
9,010.jpg,Baguette,244,Unbalance,Low quality,2014:10:03 12:59:04
10,011.jpg,Strawberries smothie,102,Unbalance,Good quality,2014:10:03 13:46:04
11,012.jpg,Raisin sugar tablets,264,Unbalance,Low quality,2014:10:04 09:16:41
12,013.jpg,lemon yogurt,184,Balance,Medium quality,2014:10:04 09:29:58
13,014.jpg,"Meatloaf with coliflower, baked red peppers,ba...",743,Unbalance,Good quality,2014:10:04 12:19:04
14,015.jpg,gatorade,187,Unbalance,Low quality,2014:10:04 19:30:30
15,016.jpg,"Iceberg lettuce with olive oil and vinegar, ha...",1202,Unbalance,Medium quality,2014:10:04 19:33:35
16,017.jpg,"Grapefruit yogurt, kiwi and bread and coffee",384,Unbalance,Good quality,2014:10:05 06:33:31
17,018.jpg,Apple and raisinsugar tablets,374,Unbalance,Medium quality,2014:10:05 09:56:05
18,019.jpg,Boiled fennel with pasta and chicken,503,Unbalance,Medium quality,2014:10:05 12:15:55
19,020.jpg,Biscuit vital,383,Unbalance,Low quality,2014:10:05 12:33:55
20,021.jpg,Solevita multivitamin,195,Unbalance,Low quality,2014:10:05 18:21:39
21,022.jpg,Solevita multivitamin,195,Unbalance,Low quality,2014:10:05 18:21:45
22,023.jpg,"Lettuce salad witholive oil, asiago cheese, ha...",2303,Unbalance,Medium quality,2014:10:05 20:32:23
23,024.jpg,Lime yogurt and bread,377,Unbalance,Medium quality,2014:10:06 06:29:32
24,025.jpg,lemon yogurt,184,Balance,Medium quality,2014:10:06 09:20:15
25,026.jpg,Roasted beef sandwich and kaggi chocolate and ...,1172,Unbalance,Low quality,2014:10:06 12:39:08

In [16]:
insulin_data

          date      time  fast_insulin  slow_insulin  comment
0   2014-10-01  10:06:00             7           NaN      NaN
1   2014-10-01  16:50:00             4           NaN      NaN
2   2014-10-01  19:28:00             6           NaN      NaN
3   2014-10-01  22:27:00             8           NaN      NaN
4   2014-10-01  23:48:00             0          31.0      NaN
5   2014-10-02  00:45:00             2           NaN      NaN
6   2014-10-02  10:10:00             3           NaN      NaN
7   2014-10-02  12:34:00            12           NaN      NaN
8   2014-10-02  21:24:00             5           NaN      NaN
9   2014-10-02  22:24:00             4          31.0      NaN
10  2014-10-03  06:11:00             9           NaN      NaN
11  2014-10-03  09:30:00             3           NaN      NaN
12  2014-10-03  19:05:00             7           NaN      NaN
13  2014-10-03  22:35:00             2          31.0      NaN
14  2014-10-04  06:10:00            12           NaN      NaN
15  2014-10-04  12:05:00             7           NaN      NaN
16  2014-10-04  20:06:00             8           NaN      NaN
17  2014-10-05  06:12:00            12           NaN      NaN
18  2014-10-05  11:30:00            11           NaN      NaN

## Accelerometer Subset

In [ ]:
# acclerometer, heart rate, breathing rate, and activity data
sum1 = pd.read_csv('/kaggle/input/datasets/sarabhian/d1namo-ecg-glucose-data/diabetes_subset_sensor_data/diabetes_subset_sensor_data/001/sensor_data/2014_10_01-10_09_39/2014_10_01-10_09_39_Summary.csv')

sum2 = pd.read_csv('/kaggle/input/datasets/sarabhian/d1namo-ecg-glucose-data/diabetes_subset_sensor_data/diabetes_subset_sensor_data/001/sensor_data/2014_10_02-10_56_44/2014_10_02-10_56_44_Summary.csv')
sum3 = pd.read_csv('/kaggle/input/datasets/sarabhian/d1namo-ecg-glucose-data/diabetes_subset_sensor_data/diabetes_subset_sensor_data/001/sensor_data/2014_10_03-06_36_24/2014_10_03-06_36_24_Summary.csv')
sum4 = pd.read_csv('/kaggle/input/datasets/sarabhian/d1namo-ecg-glucose-data/diabetes_subset_sensor_data/diabetes_subset_sensor_data/001/sensor_data/2014_10_04-06_34_57/2014_10_04-06_34_57_Summary.csv')

summary = pd.concat([sum1, sum2, sum3, sum4])
summary = summary.drop(columns=['TxPower', 'RSSI', 'AuxADC1', 'AuxADC2', 'AuxADC3', 'DeviceTemp', 'ROGTime', 'BatteryLevel',
                                'BatteryVolts', 'VerticalMin', 'VerticalPeak', 'LateralPeak', 'LateralMin', 
                                'HRConfidence', 'HRV', 'SystemConfidence', 'BRConfidence', 'BRNoise', 'GSR', 'ROGState', 
                                'LinkQuality', 'CoreTemp', 'StatusInfo', 'ECGAmplitude', 'ECGNoise'])

summary['Time'] = pd.to_datetime(summary['Time'], format='%m/%d/%Y %H:%M:%S.%f')

summary['Time'] = summary['Time'].apply(lambda x: x.replace(month=x.day, day=x.month))
summary.sort_values(by='Time', inplace=True)

summary

"\nsum2 = pd.read_csv('/kaggle/input/datasets/sarabhian/d1namo-ecg-glucose-data/diabetes_subset_sensor_data/diabetes_subset_sensor_data/001/sensor_data/2014_10_02-10_56_44/2014_10_02-10_56_44_Summary.csv')\nsum3 = pd.read_csv('/kaggle/input/datasets/sarabhian/d1namo-ecg-glucose-data/diabetes_subset_sensor_data/diabetes_subset_sensor_data/001/sensor_data/2014_10_03-06_36_24/2014_10_03-06_36_24_Summary.csv')\nsum4 = pd.read_csv('/kaggle/input/datasets/sarabhian/d1namo-ecg-glucose-data/diabetes_subset_sensor_data/diabetes_subset_sensor_data/001/sensor_data/2014_10_04-06_34_57/2014_10_04-06_34_57_Summary.csv')\n\nsummary = pd.concat([sum1, sum2, sum3, sum4])\nsummary = summary.drop(columns=['TxPower', 'RSSI', 'AuxADC1', 'AuxADC2', 'AuxADC3', 'DeviceTemp', 'ROGTime', 'BatteryLevel',\n                                'BatteryVolts', 'VerticalMin', 'VerticalPeak', 'LateralPeak', 'LateralMin', \n                                'HRConfidence', 'HRV', 'SystemConfidence', 'BRConfidence', 'BRNoise', 'GSR', 'ROGState', \n                                'LinkQuality', 'CoreTemp', 'StatusInfo', 'ECGAmplitude', 'ECGNoise'])\n\nsummary['Time'] = pd.to_datetime(summary['Time'], format='%m/%d/%Y %H:%M:%S.%f')\n\nsummary['Time'] = summary['Time'].apply(lambda x: x.replace(month=x.day, day=x.month))\nsummary.sort_values(by='Time', inplace=True)\n\nsummary\n"

In [ ]:
# split into different categories

#physilogical / vital
phys_state = summary[['HR', 'BR', 'HRV', 'CoreTemp', 'SkinTemp', 'GSR']]

#movement / activity
activity = summary[['Activity', 'Posture', 'PeakAccel', 'VerticalMin', 'VerticalPeak',
                    'LateralMin', 'LateralPeak', 'SagittalMin', 'SagittalPeak'
                    ]]

#ECG / heart signal quality
ecg_quality = summary[['ECGAmplitude', 'ECGNoise', 'HRConfidence']]

#breathing signal quality
breathing = summary[['BRAmplitude', 'BRNoise', 'BRConfidence']]

#overall data quality and time
sum_data = summary[['Time', 'SystemConfidence']]

#device hardware
device = summary[['BatteryVolts', 'BatteryLevel', 'DeviceTemp', 'StatusInfo']]

#wireless/communication
comm = summary[['LinkQuality', 'RSSI', 'TxPower']]

#system/receiver
rog = summary[['ROGState', 'ROGTime']]

#auxiliary sensor inputs
aux = summary[['AuxADC1', 'AuxADC2', 'AuxADC3']]

Index(['Time', 'HR', 'BR', 'SkinTemp', 'Posture', 'Activity', 'PeakAccel',
       'BatteryVolts', 'BatteryLevel', 'BRAmplitude', 'BRNoise',
       'BRConfidence', 'ECGAmplitude', 'ECGNoise', 'HRConfidence', 'HRV',
       'SystemConfidence', 'GSR', 'ROGState', 'ROGTime', 'VerticalMin',
       'VerticalPeak', 'LateralMin', 'LateralPeak', 'SagittalMin',
       'SagittalPeak', 'DeviceTemp', 'StatusInfo', 'LinkQuality', 'RSSI',
       'TxPower', 'CoreTemp', 'AuxADC1', 'AuxADC2', 'AuxADC3'],
      dtype='object')